### ISSUE TITLE
is PushNamespaceFiles completely broken, or I'm crazy. 

### ISSUE THREAD

**Issue by kundeng** [kestra-io/plugin-git#105]
### Describe the issue

I have the following task and it doesn't do pushnamespacefiles at all!  Instead the log shows it's pushing flows!!!

I have a loop there because originally I thought it only does the namespace itself and doesn't include child namespaces and that's why I'm not seeing any files created in the git repo. 

```
    - id: push_namespace_files
      type: io.kestra.plugin.git.PushNamespaceFiles
      namespace: "{{ taskrun.value }}"
      files: "*"
      gitDirectory: "{{'_files/' ~ taskrun.value}}"
      url: "{{ inputs.gitUrl }}"
      username: "{{ inputs.gitUsername }}"
      password: "{{outputs.render_passwd.values.passwd}}"
      branch: "{{ inputs.branchNamespaceFiles }}"
      commitMessage: "{{ render(inputs.commitMessageNamespaceFiles) }}"
      dryRun: false
      
```

The kestra logs shows it's pushing and comparing flow files instead of named space files.  

### Environment

- Kestra Version: develop

**Comment by Ben8t** [comment]
Hello @kundeng, can you give us your full flow please ? Did you try just with one simple file to check (without any loop) if it works for your case ?

**Comment by anna-geller** [comment]
+1 please add full example and please try without a loop as those properties might not be dynamic

**Comment by kundeng** [comment]
I started without the loop.  The log shows its doing push_flows twice as the first task is push the flows.  I do have namespaces that have files in them and I don't see them in my git repo. 


```
id: push-to-git
namespace: umhs.cdis.util

inputs:
  - id: sourceNamespace
    type: STRING
    required: true
    defaults: umhs
  - id: targetNamespace
    type: STRING
    required: true
    defaults: umhs
  - id: gitUrl
    type: STRING
    required: true
    defaults: "https://git.umms.med.umich.edu/empf/kestra/scripts"
  - id: gitUsername
    type: STRING
    required: true
    defaults: "kundeng"
  - id: gitPassword
    type: STRING
    required: true
    defaults: "{{kv('GITLAB_ACCESS_TOKEN')}}"
  - id: branchFlows
    type: STRING
    required: true
    defaults: kestra
  - id: branchNamespaceFiles
    type: STRING
    required: true
    defaults: kestra
  - id: commitMessageFlows
    type: STRING
    required: false
    defaults: "add flows {{ now() }}"
  - id: commitMessageNamespaceFiles
    type: STRING
    required: false
    defaults: "add namespace files {{ now() }}"
  - id: dryRun
    type: BOOLEAN
    required: false
    defaults: true

tasks:
  - id: render_passwd
    type: io.kestra.plugin.core.output.OutputValues
    values:
      passwd: "{{render(inputs.gitPassword, recursive=true) }}"

  - id: push_flows
    type: io.kestra.plugin.git.PushFlows
    sourceNamespace: "{{ inputs.sourceNamespace }}"
    targetNamespace: "{{ inputs.targetNamespace }}"
    flows: "*"
    includeChildNamespaces: true
    gitDirectory: "_flows"
    url: "{{ inputs.gitUrl }}"
    username: "{{ inputs.gitUsername }}"
    password: "{{outputs.render_passwd.values.passwd}}"
    branch: "{{ inputs.branchFlows }}"
    commitMessage: "{{ render(inputs.commitMessageFlows) }}"
    dryRun: false

  - id: push_namespaces
    type: io.kestra.plugin.core.flow.ForEach
    values: ["umhs.cdis.util", "umhs.cdis.system", "umhs.cdis.test"]
    tasks:

    - id: push_namespace_files
      type: io.kestra.plugin.git.PushNamespaceFiles
      namespace: "{{ taskrun.value }}"
      files: "*"
      gitDirectory: "{{'_files/' ~ taskrun.value}}"
      url: "{{ inputs.gitUrl }}"
      username: "{{ inputs.gitUsername }}"
      password: "{{outputs.render_passwd.values.passwd}}"
      branch: "{{ inputs.branchNamespaceFiles }}"
      commitMessage: "{{ render(inputs.commitMessageNamespaceFiles) }}"
      dryRun: false

triggers:
  - id: every_full_hour
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"
```

**Comment by Ben8t** [comment]
Can you try with `files: "/*"` please?

What's your intent here? ie. do you want to only push files at the root for your folder or do you want to push everything (also nested folder/files)?


👉 to push only root files: `/*`
👉 to push everything (including nested folders): `**`

**Comment by kundeng** [comment]
doesn't work.  

No matter what I do, I'm only seeing flows getting pushed and not namespace files.

**Comment by Ben8t** [comment]
Using `**` in `io.kestra.plugin.git.PushNamespaceFiles` works on my side. Here is a working reproducer:

```yaml
id: push-to-git
namespace: company.dev

inputs:
  - id: sourceNamespace
    type: STRING
    required: true
    defaults: company.dev
  - id: targetNamespace
    type: STRING
    required: true
    defaults: company.prod
  - id: gitUrl
    type: STRING
    required: true
    defaults: "https://github.com/Ben8t/git-demo-kestra"
  - id: gitUsername
    type: STRING
    required: true
    defaults: "Ben8t"
  - id: branchFlows
    type: STRING
    required: true
    defaults: test_bis2
  - id: branchNamespaceFiles
    type: STRING
    required: true
    defaults: test_bis2
  - id: commitMessageFlows
    type: STRING
    required: false
    defaults: "add flows {{ now() }}"
  - id: commitMessageNamespaceFiles
    type: STRING
    required: false
    defaults: "add namespace files {{ now() }}"
  - id: dryRun
    type: BOOLEAN
    required: false
    defaults: false


tasks:

  - id: push_flows
    type: io.kestra.plugin.git.PushFlows
    sourceNamespace: "{{ inputs.sourceNamespace }}"
    targetNamespace: "{{ inputs.targetNamespace}}}"
    flows: "*"
    includeChildNamespaces: true
    gitDirectory: "_flows"
    url: "{{ inputs.gitUrl}}"
    username: "{{ inputs.gitUsername }}"
    password: "{{ secret('GH_TOKEN') }}"
    branch: "{{ inputs.branchFlows }}"
    dryRun: false

  - id: push_namespaces
    type: io.kestra.plugin.core.flow.ForEach
    values: ["company.dev.unit1", "company.dev.unit2"]
    tasks:

    - id: push_namespace_files
      type: io.kestra.plugin.git.PushNamespaceFiles
      namespace: "{{ taskrun.value }}"
      files: "**"
      gitDirectory: "{{'_files/' ~ taskrun.value}}"
      url: "{{ inputs.gitUrl}}"
      username: "{{ inputs.gitUsername}}"
      password: "{{ secret('GH_TOKEN') }}"
      branch: "{{ inputs.branchNamespaceFiles }}"
      dryRun: false
```

![image](https://github.com/user-attachments/assets/5839af15-5f8c-43ae-a22f-9d613bfc05b9)
![image](https://github.com/user-attachments/assets/3dd80bc6-5e69-4b0a-a0e1-5a5ebaf011e7)

I updated the documentation example with good glob pattern https://github.com/kestra-io/plugin-git/pull/106/files

I'm closing for now as I'm not able to reproduce on my end. Please reopen if you still faces issue.
