### ISSUE TITLE
Git commit returned by self-hosted GitLab returns 404 Not Found

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-git#109]
### Feature description

When using e.g. `PushNamespaceFiles`, the commit URL logged by the task returns 404

it seems that the structure of host/project/repo/kestra_namespace/commit/commit_hash is wrong, maybe the kestra_namespace there is not needed? needs to be reproduced with GitLab - @Ben8t maybe you can try that on GitLab?

**Comment by Ben8t** [comment]
Can't reproduce but not sure I got it right 🤔 

![Image](https://github.com/user-attachments/assets/b61ea573-df92-4fc5-889d-dbd8052122b5)

```yaml
id: gitlab
namespace: qa.ben

variables:
  gh_token: "XXXX"

tasks:
  - id: push_ns
    type: io.kestra.plugin.git.PushNamespaceFiles
    namespace: "{{ flow.namespace }}"
    url: https://gitlab.com/kestra-demo/git_demo.git
    password: "{{ vars.gh_token }}"
    username: bpimpaud
    branch: test
    dryRun: false
```
