### ISSUE TITLE
Git Sync Flows output is not parsable as json

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-git#119]
### Describe the issue

```yaml
id: git_sync_sanity_check3
namespace: qa

tasks:
  - id: git_sync
    type: io.kestra.plugin.git.SyncFlows
    url: https://github.com/kestra-io/blueprints
    gitDirectory: sanitychecks
    targetNamespace: qa.sanitycheck
    includeChildNamespaces: true
    dryRun: false
```

![image](https://github.com/user-attachments/assets/8059b93d-c971-4a38-97ad-2f7d22d0a047)

You can see that the keys don't have quote: it makes the `"{{ read(outputs.git_sync.flows) }}"` not usable.

Current workaround is to parse the file properly using shell command:
```
  - id: shell
    type: io.kestra.plugin.scripts.shell.Commands
    inputFiles:
      input.txt: "{{ outputs.git_sync.flows }}"
    commands:
      - echo "[$(cat input.txt | sed 's/{\([^}]*\)}/{\n\1\n}/g' | sed 's/\([^":,{]\+\):/"\1":/g' | sed 's/}$/},/' | sed '$ s/,$//')] " > output.json
    outputFiles:
      - output.json
 ```

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
looks like a misunderstanding of the output format:

```yaml
id: git_sync_sanity_check3
namespace: qa

tasks:
  - id: git_sync
    type: io.kestra.plugin.git.SyncFlows
    url: https://github.com/kestra-io/blueprints
    gitDirectory: sanitychecks
    targetNamespace: qa.sanitycheck
    includeChildNamespaces: true
    dryRun: false
  
  - id: to_json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.git_sync.flows }}"
```

let's discuss via Slack first if you have any other issue with this 👍
