### ISSUE TITLE
KestraConstraintViolationException: get.docVersion: must not be null

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-git#124]
### Describe the issue

Using the GitSyncFlows I got the following error on develop (postgress-oss.preview)

![image](https://github.com/user-attachments/assets/08afc08e-8df3-4e5b-a085-4107fb0a43de)

```yaml
id: test_git_sync
namespace: sanitychecks

tasks:
  - id: git_sync
    type: io.kestra.plugin.git.SyncFlows
    url: https://github.com/kestra-io/blueprints
    gitDirectory: sanitychecks
    targetNamespace: integration
    includeChildNamespaces: true
```

### Environment

- Kestra Version: develop
