### ISSUE TITLE
git.PushDashboards isn't working and lack required properties

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-git#141]
### Describe the issue

Using a basic example such as the following:

```yaml
id: starling_682013
namespace: dev.ben

tasks:
  - id: push_dashboard
    type: io.kestra.plugin.git.PushDashboards
    username: Ben8t
    password: ghp_XXX
    url: https://github.com/Ben8t/test-repo
```

I got this error, which doesn't bring that much information on how to troubleshoot:

![Image](https://github.com/user-attachments/assets/baa2e129-e104-4394-8f19-331c9a6be4c7)

FYI, my repository is a private one without any other specificity.

Also, looking at the task documentation, I can't see required properties. I would expect at least `url` right?

![Image](https://github.com/user-attachments/assets/e8808364-d40e-4a5c-ada4-e775fa29f2cf)

### Environment

- Kestra Version: develop

**Comment by mgabelle** [comment]
I am gonna look at it.

Regarding the URL property not being required I don't know why exactly but PushDashboards is based AbstractGitTask which is used by a lot of tasks such as PushFlows or PushNamespaces. If you check these you'll notice that URL is not mandatory either. I don't know if it was designed this way or it's been forgotten.

**Comment by Ben8t** [comment]
And I also have the same issue with `git.SyncDashboard`

```yaml
id: starling_682013
namespace: dev.ben

tasks:
  - id: push_dashboard
    type: io.kestra.plugin.git.SyncDashboards
    username: Ben8t
    password: ghp_XXXX
    url: https://github.com/Ben8t/test-repo
    gitDirectory: _dashboards
```

![Image](https://github.com/user-attachments/assets/265a05e6-be42-459a-9bd4-ea8772bc3c6a)

Here is my repository with a basic yaml file in there:

![Image](https://github.com/user-attachments/assets/70634950-5960-4df4-ac92-8f7de4ac96a9)

**Comment by mgabelle** [comment]
It really is weird..
I am able to reproduce on preview but not with unit tests. I will continue to investigate

**Comment by mgabelle** [comment]
Following flow is working on preview OSS but failed on preview EE
```
id: push_dashboards
namespace: mgabelle.tests.git

tasks:
  - id: push_dashboard
    type: io.kestra.plugin.git.PushDashboards
    username: mgabelle
    password: ghp_xxxxxxxx
    url: https://github.com/mgabelle/plugin-git-test.git
```

Preview OSS:
![Image](https://github.com/user-attachments/assets/c7e60690-4a70-4c1e-adc8-bb9bf2c9d4bf)

Preview EE : 

![Image](https://github.com/user-attachments/assets/4c566e0f-3f76-4fbd-bb9b-1f69d61637c6)

On which platform are you testing ?
