### ISSUE TITLE
PushFlows does not delete files unless wild card provided

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-git#147]
### Describe the issue

With this below task, assume you have 2 flows, `flow1` and `flow2`

Run the PushFlows task to sync these flows to your repo. 

Now, in Kestra delete `flow1`. Execute the flow again but this time provide input as `flow1,flow2`. Notice that no change will occur. 

Now execute once again, this time with input back to `"*"` . Flow `flow1` will be deleted from git repo

```
inputs:
  - id: flows
    type: STRING
    defaults: "*"
tasks:
  - id: push_flows
    type: io.kestra.plugin.git.PushFlows
    sourceNamespace: solutions
    targetNamespace: solutions
    flows: "{{inputs.flows}}"
    includeChildNamespaces: true
    gitDirectory: _flows
    branch: develop
    commitMessage: add flows {{ now() }}
```

### Environment

- Kestra Version: 0.22.7
