### ISSUE TITLE
Add privateKey property to the AbstractGitTask to support SSH key-based authentication for all Git tasks

### ISSUE THREAD

**Issue by smooth-baking-powder** [kestra-io/plugin-git#172]
### Describe the issue

This Flow not work with the WorkingDirectory inputFiles. Before i used the deprecated LocalFiles and it worked fine.

```
id: dev-test
namespace: dev

tasks:
  - id: start
    type: io.kestra.plugin.core.flow.WorkingDirectory
    inputFiles:
      id_rsa: "test"


    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.SyncNamespaceFiles
        namespace: prod
        gitDirectory: _files # optional; set to _files by default
        delete: false # optional; by default, it's set to false to avoid destructive behavior
        url: "{{ globals['repository-url'] }}"
        branch: "{{ globals['repository-branch'] }}"
        username: "{{ globals['repository-username'] }}"
        password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
        dryRun: true
```

Log:
```
2024-06-07T06:40:15.026Z INFO Provided 1 input(s).
2024-06-07T06:40:16.187Z INFO Start cloning from 'https://gitlab.xy.xy/xy/xy'
2024-06-07T06:40:16.204Z ERROR Destination path "spgOiPTaewpXqQS8vgGL0" already exists and is not an empty directory
```
![image](https://github.com/kestra-io/plugin-git/assets/21257329/f46efe91-1998-436c-b458-f1fe23fdcb59)

If i use the old "LocalFiles" it works:

```
id: dev-test
namespace: dev

tasks:
  - id: start
    type: io.kestra.plugin.core.flow.WorkingDirectory

    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.SyncNamespaceFiles
        namespace: prod
        gitDirectory: _files # optional; set to _files by default
        delete: false # optional; by default, it's set to false to avoid destructive behavior
        url: "{{ globals['repository-url'] }}"
        branch: "{{ globals['repository-branch'] }}"
        username: "{{ globals['repository-username'] }}"
        password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
        dryRun: true
      
      - id: load_ssh_key
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          id_rsa: "{{ secret('SSH_KEY') }}"
```

Log:
```
2024-06-07T06:43:30.430Z INFO Start cloning from 'https://gitlab.c-lab.one/c-lab/automatisierung'
2024-06-07T06:43:31.851Z INFO Provided 1 input(s).
2024-06-07T06:43:31.857Z INFO Captured 0 output(s).
```
![image](https://github.com/kestra-io/plugin-git/assets/21257329/ea81eba4-f1bd-4250-878b-c9bc6ea4f01a)

### Environment

- Kestra Version: 0.17.1
- Operating System (OS/Docker/Kubernetes): Debian/Docker

**Comment by Pradumnasaraf** [comment]
It's working! cc @smooth-baking-powder

```yaml
id: git_clone_into_workingdir_with_input_files
namespace: qa.git

tasks:
  - id: workdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    inputFiles:
      preexisting_marker.txt: "i was here before the clone"
    tasks:
      - id: list_before_clone
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        commands:
          - ls -la
          - cat preexisting_marker.txt

      - id: clone_into_nonempty_root
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/blueprints
        branch: main

      - id: list_after_clone
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        commands:
          - ls -la
          - echo "---marker contents---"
          - cat preexisting_marker.txt
          - echo "---repo present?---"
          - test -d .git && echo ".git directory present" || (echo ".git MISSING" && exit 1)
          - test -f README.md && echo "README.md from repo present" || echo "README.md not found at root (may be ok if repo has no README)"

      - id: clone_into_nonempty_subdir
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/examples
        branch: main
        directory: nested_repo

      - id: list_subdir_after
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        commands:
          - ls -la nested_repo
          - test -d nested_repo/.git && echo "nested .git present" || (echo "nested .git MISSING" && exit 1)

  - id: workdir_for_sync
    type: io.kestra.plugin.core.flow.WorkingDirectory
    inputFiles:
      id_rsa: "test"
    tasks:
      - id: list_before_sync
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        commands:
          - ls -la
          - cat id_rsa

      - id: sync_namespace_files_dryrun
        type: io.kestra.plugin.git.SyncNamespaceFiles
        namespace: qa.git
        gitDirectory: flows
        url: https://github.com/kestra-io/blueprints
        branch: main
        delete: false
        dryRun: true

      - id: list_after_sync
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        commands:
          - ls -la
          - echo "---id_rsa contents---"
          - cat id_rsa
          - test -f id_rsa && echo "id_rsa survived sync" || (echo "id_rsa MISSING after sync" && exit 1)

```
