### ISSUE TITLE
Pushing only specific Flow

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-git#36]
### Feature description

When using the `git.Push` task, it doesn't seem possible to push only one flow or specific ones with the `flows` property.

I tried with the following, using `addFilesPattern` on the `_flows` directory but it doesn't seem to work (I also tried with `_flows/dev.gitPush.yml`)

```
id: gitPush
namespace: dev
tasks:
  - id: "push"
    type: "io.kestra.plugin.git.Push"
    addFilesPattern:
      - _flows/gitPush
    flows:
      enabled: true
      gitDirectory: flows
    namespaceFiles:
      enabled: true
    branch: test-git-ops # mandatory, we'll create the branch if not exists
    url: https://github.com/Ben8t/kestra_prod
    username: Ben8t
    password: '{{ secret("GITHUB") }}'
    commitMessage: "test" # required
```
