### ISSUE TITLE
`git.Sync`- Flows arranged in sub directories aren't be parsed

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-git#45]
### Expected Behavior

Having everything under `_flows` being parsed. Also the possibility to arrange flows in nested namespace in subfolders

### Actual Behaviour

When having the following repository structure:
```
_flows/
  namespace_a/
    git-sync.yml
    test.yml
```

With `test.yml`:
```yaml
id: test
namespace: namespace_a

tasks:

  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
```

`git-sync.yml` as:

```yaml
id: git-sync
namespace: integration
tasks:

  - id: git-sync
    type: io.kestra.plugin.git.Sync
    url: https://github.com/Ben8t/kestra_prod
    branch: test-git-ops
    username: Ben8t
    password: "{{ secret('GITHUB') }}"
    
triggers:
  - id: every_minute
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
```

The git-sync flow raises this error:

![image](https://github.com/kestra-io/plugin-git/assets/46634684/884374fb-aad5-4280-8b89-8a13fbc467a0)

Having nested directories in `_flows` doesn't seem to work; it's not parsed + the logs is not very informative.

### Environment Information

- Kestra Version: 0.14.4
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): us.kestra.cloud
- Java Version (If not docker):
