### ISSUE TITLE
`git.Push` can use custom flow folder, while `git.Sync` can't

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-git#46]
### Feature description

With the `git.Push` task, it's possible to override the `_flows` folder to use custom one. This is very handy while git repository structure can be very specific to each user.

```yaml
- id: "push"
    type: "io.kestra.plugin.git.Push"
    flows:
      enabled: true
      gitDirectory: flows
    namespaceFiles:
      enabled: true
    branch: test-git-ops # mandatory, we'll create the branch if not exists
    url: https://github.com/Ben8t/kestra_prod
    username: Ben8t
    password: '{{ secret("GITHUB") }}'
    commitMessage: "test" # required
```

However the  `git.Sync` task can't use a custom `_flows` folder. It's not possible to map one.

```yaml
id: git-sync
namespace: integration
tasks:

  - id: git-sync
    type: io.kestra.plugin.git.Sync
    url: https://github.com/Ben8t/kestra_prod
    branch: test-git-ops
    username: Ben8t
    gitDirectory: my_flows # this doesn't work
    namespaceFilesDirectory: ns_script
    password: "{{ secret('GITHUB') }}"
    
triggers:
  - id: every_minute
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
    ```
