### ISSUE TITLE
How to use a proxy in io.kestra.plugin.git.Clone to clone inside of Kuberntes Cluster

### ISSUE THREAD

**Issue by Trunken** [kestra-io/plugin-git#51]
### Issue description

Hello,

currently we are trying to use Kestra as our orchestrator. We are running it inside a Kubernetes Cluster behind a proxy. Now we want to use the clone task but it does not work.

We already set up the env variables http_proxy, https_proxy and no_proxy in lowercase and uppercase but it did not help.

```yaml  
id: test-clone
namespace: clone

tasks:
- id: "clone"
  type: "io.kestra.plugin.git.Clone"
  url: XXXX
  branch: main
  username: "{{ secret('GIT_USERNAME') }}"
  password: "{{ secret('GIT_ACCESSTOKEN') }}"
```

How do we have to configure the task so we can clone behind our proxy?

Thank you
