### ISSUE TITLE
If `sourceNamespace` and `targetNamespace` are left blank, namespace is `null` inside of Git repository

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-git#79]
### Expected Behavior

When committing to git with `sourceNamespace` and `targetNamespace` properties not set, the namespace in the flow should be the same as it was in Kestra

### Actual Behaviour

It sets the namespace to null
```yaml
id: push_to_git
namespace: system
```
https://github.com/wrussell1999/test

### Steps To Reproduce

```yaml
id: push_to_git
namespace: system

tasks:
  - id: commit_and_push
    type: io.kestra.plugin.git.PushFlows
    username: wrussell1999
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    url: https://github.com/wrussell1999/test
    branch: main
    gitDirectory: flows
    commitMessage: "changes to kestra flows"
```

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
