### ISSUE TITLE
`EachParallel` reports successful parallel commits but commits not visible in Git Repository

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-git#81]
### Expected Behavior

When using `EachParallel` to bulk commit multiple namespaces at once, all commits should appear in GitHub. If this is not possible due to the nature of committing multiple times to the same repository, it should fail or mentioned that it's not possible.

Looks like Git PushFlows is rewriting the history, rather than pushing a new commit on top. If that's the intention, we should clear that up in the documentation as that prevents parallel use of PushFlows. This commit was accessed from the Kestra logs: 
![Screenshot 2024-06-20 at 17 18 26](https://github.com/kestra-io/plugin-git/assets/34094921/6bca012d-29fb-4b6e-acf2-be0c1c1051f8)

### Actual Behaviour

When using `EachParallel` to bulk commit multiple namespaces at once, it comes back as successful but not all of the commits are visible.
![Screenshot 2024-06-20 at 17 17 21](https://github.com/kestra-io/plugin-git/assets/34094921/564d4c21-279b-4de8-a661-8b30034e8600)
![Screenshot 2024-06-20 at 17 17 28](https://github.com/kestra-io/plugin-git/assets/34094921/c7ea4f76-c040-4f9c-8e59-66f1058606f1)

### Steps To Reproduce

```yaml
id: push_to_git
namespace: system

tasks:
  - id: fetch_namespaces
    type: io.kestra.plugin.core.http.Request
    uri: http://host.docker.internal:8082/api/v1/flows/distinct-namespaces

  - id: loop_namespaces
    type: io.kestra.plugin.core.flow.EachParallel
    value: "{{outputs.fetch_namespaces.body}}"
    tasks:
      - id: commit_and_push
        type: io.kestra.plugin.git.PushFlows
        username: wrussell1999
        password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
        url: https://github.com/wrussell1999/test
        branch: main
        sourceNamespace: "{{ taskrun.value }}"
        targetNamespace: "{{ taskrun.value }}"
        gitDirectory: "flows/{{ taskrun.value }}"
        commitMessage: "parallel: changes to kestra flows for {{ taskrun.value }}"
```

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
