### ISSUE TITLE
How to push multiple flows to production using gitPush?

### ISSUE THREAD

**Issue by gvanderweerd** [kestra-io/plugin-git#99]
### Issue description

As discussed on slack I have opened an issue. See slack chat below:
https://kestra-io.slack.com/archives/C03FQKXRK3K/p1728459250919099

**Comment by gvanderweerd** [comment]
Thanks for your response! here is the info from the slack chat:

**Giel:**
At my company we have set up a dev and a prod environment of kestra. We are now looking to design a convenient system to push flows from production using git pushflows:
https://kestra.io/docs/best-practices/from-dev-to-prod
https://kestra.io/plugins/plugin-git/tasks/io.kestra.plugin.git.pushflows
Now we want to have control over which namespace files and which flows we push to production such that we do not have to alter the code of the flow that pushes to production everytime we want to. We tried to use inputs (ARRAY, MULTISELECT, and YAML) but it is not working since the ArrayList data type is not accepted by the io.kestra.plugin.git.PushFlows.
If we cast an ArrayList into string like: flows: “{{ inputs.flows | yaml }}”, the flow will execute successfully but no changes will be found.
Does anyone have experience with setting up such a system in kestra?

**Benoit:**
Hello Giel !
Did you try by settings a list of glob patterns (flows: "{{input.flows}}" with input.flows being an array) ?
I will try something in my end too

**Giel:**
We tried and found 2 working solutions:
    flows: "*"  # optional list of glob patterns; by default, all flows are pushed #working but dont need all
    flows: '{{ inputs.string }}' #working but restricts us to 1 flow at the time
We also tried a lot of other things among which:
flows: "{{ inputs.flows }}"
flows: "{{ inputs.flows | join(',') }}"
flows: "{{ inputs.flows | join('\n') }}"
flows: "{{ inputs.dropdown_multi }}"
flows: "{{ inputs.yaml | yaml }}"
If there is no easy way to manually input a list of flows that we want we will just stick to pushing 1 flow at the time but just wanted to verify if we are overlooking something here or are using it wrong.

it accept string and the string must contain only one flow. If its multiple flows in that string it wont detect the changes

Hi Benoit were you able to replicate something that could solve my problem? Or are we using it in the wrong way? If the conclusion is that we can only do 1 flow or all flows than that is also a valid conclusion. I just want to prevent that we keep developing endlessly to try and solve a problem that cannot be solved currently.

**Comment by EverybodyGetBackToWork** [comment]
+1 for this, have tried to achieve using an Array (list of flows) such as ["test", "test1"] which works if explicitly stated in the flow but the syntax is rejected when this is passed as an input.

**Comment by anna-geller** [comment]
@Ben8t can you ask Matt to add dynamic properties for Git tasks and once that's done try to reproduce it? I feel this looks like an issue that flows is not dynamic ATM, that's why it cannot be passed from Inputs this way

**Comment by Ben8t** [comment]
Same behavior here on develop:

```yaml
id: push_flows
namespace: qa.ben

inputs:
  - id: flows
    type: ARRAY
    itemType: STRING

tasks:
  - id: push
    type: io.kestra.plugin.git.PushFlows
    url: https://gitlab.com/kestra-demo/git_demo.git
    username: bpimpaud
    password: "xxxx"
    dryRun: false
    sourceNamespace: "{{ flow.namespace }}"
    targetNamespace: prod
    branch: test2
    flows: "{{ inputs.flows }}"
```

![Image](https://github.com/user-attachments/assets/ceebfc77-a841-4b50-aca2-8aefc454684b)

Nothing is pushed (tested on a fresh new branch).

It sounds very similar to this [issue](https://github.com/kestra-io/plugin-fs/issues/168) where inputs array can't be mapped to actual property.

@mgabelle any view on this?

**Comment by mgabelle** [comment]
I think flows is more a list of dynamic properties rather than a dynamic property itself. Looking at the code it has not been designed to deal with a list directly.

It is working with this syntax : 
```
flows:
   - "{{ inputs.flow1 }}"
   - "{{ inputs.flow2 }}"
```
Do you have an example of an other plugin where the use of a direct array/list work ?

**Comment by mgabelle** [comment]
Reproduced with new fixe and worked successfully :

Step 1: add 3 flows under namespace `company` with id `test-1`, `test-2`, and `hello-1`

Step 2: execute following flow 
```
id: push_flows
namespace: company.team

inputs:
  - id: flows
    type: ARRAY
    itemType: STRING
    defaults:
      - test*
      - hello*
      
tasks:
  - id: push_flows
    type: io.kestra.plugin.git.PushFlows
    branch: qa-1
    url: https://github.com/mgabelle/plugin-git-test
    commitMessage: Test add flows QA
    username: mgabelle
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    authorEmail: "mgabelle@kestra.io"
    authorName: mgabelle
    flows: "{{ inputs.flows }}"
    sourceNamespace: company
    includeChildNamespaces: true
    gitDirectory: myFlows
```

Step 4: check in repo `plugin-git-test` and flow have been successfully pushed
